services:
  web:
    build: .
    container_name: job_portal
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: job_portal_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: