name: Build on PR # to make sure the code is working before merging PR
# as if the action is not working, we will not be able to merge the PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Build
        run: npm run build